services:
  PhpArsenal\SalesforceMapperBundle\Request\ParamConverter\SalesforceParamConverter:
    arguments:
      - '@PhpArsenal\SalesforceMapperBundle\Mapper'
      - '%arsenal_salesforce_mapper.param_converter%'